name: 'Tag UPM Readme'
description: 'Tag a link in Unity Package Readme'
inputs:
  path:  # id of input
    description: 'Path to Readme'
    required: true
    default: 'Readme.md'
  major:  
    description: 'version major to add as tag'
    required: true
  minor:  
    description: 'version minor to add as tag'
    required: true
  patch:  
    description: 'version patch to add as tag'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
